# Generated by Django 5.0.2 on 2024-02-29 16:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('contact_number', models.CharField(blank=True, max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('id_or_passport', models.CharField(blank=True, max_length=13, null=True)),
                ('id_type', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=5, null=True)),
                ('youth', models.CharField(blank=True, max_length=3, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('race', models.CharField(blank=True, max_length=50, null=True)),
                ('disability', models.CharField(blank=True, max_length=50, null=True)),
                ('home_language', models.CharField(blank=True, max_length=50, null=True)),
                ('citezenship', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('unemployed_period', models.CharField(blank=True, max_length=100, null=True)),
                ('home_address', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_address', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('contract_number', models.CharField(blank=True, max_length=20, null=True)),
                ('contracted_learning_status', models.CharField(blank=True, max_length=50, null=True)),
                ('learner_enrollment_number', models.CharField(blank=True, max_length=20, null=True)),
                ('learning_programe_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('intervention', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('guardian_id_no', models.CharField(blank=True, max_length=13, null=True)),
                ('guardian_full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_contact', models.CharField(blank=True, max_length=10, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('municipality', models.CharField(blank=True, max_length=50, null=True)),
                ('town_or_city', models.CharField(blank=True, max_length=50, null=True)),
                ('urban_or_rural', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation_level', models.CharField(blank=True, max_length=1000, null=True)),
                ('job_title', models.CharField(blank=True, max_length=50, null=True)),
                ('OFO_occupation_code', models.CharField(blank=True, max_length=50, null=True)),
                ('OFO_specialization', models.CharField(blank=True, max_length=50, null=True)),
                ('OFO_occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('highest_school_qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('student_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bursary_awarded_date', models.DateField(blank=True, null=True)),
                ('bursary_completion_status', models.CharField(blank=True, max_length=50, null=True)),
                ('popi_consent', models.CharField(blank=True, max_length=10, null=True)),
                ('popi_consent_date', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
