# Generated by Django 5.0.3 on 2024-03-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_customuser_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='temporary_password_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
